### ISSUE TITLE
Incorrect delimiter in 2019-12-05 and following datasets

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/helics_benchmark_results#4]
In the datasets for 2019-12-05, 2019-12-12, and 2019-12-16 I'm seeing the incorrect delimiter related to the core type; for example:

```“BM_echo_.*[Fed|Core]/…”``` should be ```“BM_echo/.*[Fed|Core]/…”```

I'm seeing this in the following test results:
- echoResult
- echoMessage
- filter
- messageLookup
- pHold
- ring

**Comment by trevorhardy** [comment]
I've corrected the names pushed them to the "benchmark_standardize_output_format". I'll push them into master once I confirm with @phlptp or @nightlark this corrections are appropriate.

**Comment by trevorhardy** [comment]
(And for extra credit, in a separate commit, I converted "singleFed" (in all previous test results) to "singleCore" used in the latest test results. I'll push it up to master with the other changes once the they are confirmed correct.)

**Comment by phlptp** [comment]
I am not sure this possible at present.  the _SingleCore or _MultiCore is part of the benchmark name.  as in the C++ function name,  which can't have '/' in it.    There are a few cases with some work we could merge the two functions to generate the '/' like we do in one case but in other cases it is impractical.   So I am not sure we can address this.

**Comment by phlptp** [comment]
We can maybe get rid of the first underscore if that would help then _ or / could be a delimiter?

**Comment by trevorhardy** [comment]
Ahh, I see. If we could purge the underscores from the string like you suggest (I see the substring "real_time" as well; perhaps there are others) and use it as a delimiter that would be wonderful.

**Comment by nightlark** [comment]
@phlptp would probably know better, but "real_time" might be the name of a counter that's built into google benchmark.

**Comment by trevorhardy** [comment]
So far, I don't think I care about that part of the name so we might be able to squeeze by without having to convert that portion. It would be nice to always have "_" be a delimiter but we might be able to make do without such a simple statement being true.

**Comment by trevorhardy** [comment]
@phlptp updated the benchmark naming starting in the 2019-12-18 dataset. I'll go ahead and make my script robust or change the old results files to conform to the new naming convention.
