### ISSUE TITLE
Non-conforming JSON in results files

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/helics_benchmark_results#5]
The following result file was committed with a non-conforming JSON:

bm_echoResults2019-12-12_kKRb9.txt - missing closing ```]``` and ```}```

**Comment by nightlark** [comment]
Huh? It looks like it is okay: https://github.com/GMLC-TDC/helics_benchmark_results/blob/master/benchmark_results/2019-12-12/bmk_echoResults2019-12-12_kKRb9.txt#L144-L145

**Comment by nightlark** [comment]
The matching `[` is up on line 47.

**Comment by trevorhardy** [comment]
Here's the file as originally committed. I cleaned it up and pushed it back into master, thus hiding the problem.

https://github.com/GMLC-TDC/helics_benchmark_results/commit/42c8e9571b3a97b3bfd91ae526f9b350dc9f9cf1#diff-291191cd2153b024c6be0495d017ec58

**Comment by nightlark** [comment]
Actually, I'm not sure that file should be there.

**Comment by trevorhardy** [comment]
OK. Pull it from master if it shouldn't be there and I'll merge the change into the branches we're working in.

I was reporting this as a bug because it seemed that there may have still be problems in how the benchmark results files are getting written out.

**Comment by nightlark** [comment]
I'm rerunning the key benchmarks to confirm, but I think that a few of those files were from a job I cancelled after realizing that a full run would take a few hours (not good for a shared system).

**Comment by trevorhardy** [comment]
Cool. I'll look for further comments and/or commits and clean-up our branches appropriately.

**Comment by nightlark** [comment]
Alright, I removed the 3 files from the cancelled run.

**Comment by trevorhardy** [comment]
No errors in processing the files. Let's call it good.
