### ISSUE TITLE
"singleFed" and "singleCore" naming inconsistency

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/helics_benchmark_results#7]
Based on the testing in our cross-run-id comparison, it looks like some of the benchmarks are still have results under "singleFed" instead of the new name "singleCore". We need to confirm that new results use "singleCore" and change the naming in the old results.

**Comment by phlptp** [comment]
If there is still something in the later results, then we may have missed some changes in the updates to fix it.

**Comment by trevorhardy** [comment]
As a part of working on #6, the singleFed graphs went away so I'm going to close this for now. I don't think the "singleFed" data is no longer in the datagram but we'll wait for it to pop-up again before hunting this down.
